package(default_visibility=["//visibility:public"])

load("//build_defs:typescript.bzl", "ts_library")

ts_library(
    name = "one",
    srcs = glob(["**/*.ts"]),
    tsconfig = "tsconfig.json",
    module_name = "one",
)
