#!/usr/bin/env bash

set -e

if ! which bazel > /dev/null; then
  echo "Bazel is not installed. Please install it from your package manager."
  exit 1
fi

if ! NODE_BINARY=$(which node); then
  echo "Node.js not found."
  exit 1
fi

echo "Using Node.js from $NODE_BINARY"

cat > WORKSPACE <<EOD
# This file is generated by setup-bazel.sh. Do not edit it directly.

new_local_repository(
    name = "nodejs",
    path = "$(dirname "$NODE_BINARY")",
    build_file = "nodejs.BUILD",
)
EOD

echo "Written WORKSPACE."
