filegroup(
    name = "nodejs_launcher_template",
    srcs = ["nodejs_launcher_template.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "jasmine_config_template",
    srcs = ["jasmine_config_template.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "jasmine_launcher_template",
    srcs = ["jasmine_launcher_template.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "karma_launcher_template",
    srcs = ["karma_launcher_template.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rollup_config_template",
    srcs = ["rollup_config_template.js"],
    visibility = ["//visibility:public"],
)
